spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/car_booking_prod
#    url: jdbc:postgresql://dpg-cmda7a0cmk4c73ajpc90-a.singapore-postgres.render.com/car_booking_4stf
    username: postgres
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

jwt:
  issuer: cheong
  key:
    location:
      public: classpath:jwt/public.pem
      private: classpath:jwt/private.pem

logging:
  level:
    org:
      mapstruct: DEBUG
      springframework:
        web: DEBUG
        security: DEBUG
      hibernate:
        orm:
          jdbc:
            bind: TRACE

aws:
  s3:
    access-key: DO00APT2KG6NDAFEUBG9
    secret-key: LRyhqZ+ngGmfAYPnXnRwnsxi6zPerXaRQJTJwyI4Kag
    endpoint: https://volvo-sungaibesi.sgp1.digitaloceanspaces.com
    bucket-name: volvo-sungaibesi
    region: ap-southeast-1
